# LEANING NUMPY

In [132]:
import numpy as np

## THE BASICS

In [133]:
a = np.array([0,1,2,3,])
print(a)


[0 1 2 3]


In [134]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [135]:
#get the demention
a.ndim

1

In [136]:
b.ndim

2

In [137]:
#get shape
a.shape

(4,)

In [138]:
b.shape

(2, 3)

In [139]:
# get the type
a.dtype

dtype('int64')

In [140]:
b.dtype

dtype('float64')

In [141]:
#gte sixe
a.itemsize

8

In [142]:
b.itemsize

8

In [143]:
# how to gwt total size
a.nbytes


32

In [144]:
b.nbytes

48

In [145]:
a.size * a.itemsize  #another way to do this

32

## ACCESSING/CHANGING SPECIFIC ELEMENTS , ROWS, COLOUMNS,ETS

In [146]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [147]:
# get a specific element [r,c]
a[1,5]

13

In [148]:
a[1,-2]

13

In [149]:
# get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [150]:
# get aspecific coloums
a[:,4]

array([ 5, 12])

In [151]:
#getting a lil more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [152]:
a[1,1:7:3]

array([ 9, 12])

In [153]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [154]:
a[0,1:-1:2]

array([2, 4, 6])

In [155]:
#how to change some value in the lsit
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [156]:
a[:,2]=5 #for coloumns
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [157]:
a[:,2]=[1,2] #for coloumns
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3-D EXAMPLE

In [158]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [159]:
# get a specific element (work outside in)
b[0,1,1]

4

In [160]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b) # only works for arrays in same dimention

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## INTIAILIZING DIFFERIENT TYPES OF ARRAYS

In [161]:
#all zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [162]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [163]:
# any other number 
np.full((2,2),99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [164]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [165]:
# random decimal number
np.random.rand(4,2)

array([[0.57005397, 0.29642998],
       [0.2105599 , 0.86816294],
       [0.95454638, 0.65287284],
       [0.46868103, 0.52800926]])

In [166]:
np.random.rand(0,100)

array([], shape=(0, 100), dtype=float64)

In [167]:
# random interget values
np.random.randint(4,7, size=(3,3))

array([[4, 5, 4],
       [5, 6, 5],
       [4, 6, 5]])

In [168]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [169]:
#reapeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### FUNNN TIME 

1. import random 
2. generate 2 number 
3. now use that to define some shape
4. get the size of the array
5. generate those many number
5. fill the dimention with hose number

In [170]:
import random
random_rows= random.randint(1000,3000)
random_coloumns = random.randint(20,30)
random_num =np.zeros((random_rows,random_coloumns),dtype=int)
random_num.shape



(1508, 20)

In [171]:
for row in range(random_rows):
    for colomn in range(random_coloumns):
        random_num[row,colomn]=random.randint(50,500)
        

In [172]:
random_num

array([[320, 451, 180, ..., 246, 269, 312],
       [129, 437, 148, ...,  69, 121,  56],
       [223,  57, 495, ..., 492, 477, 154],
       ...,
       [183, 210, 130, ..., 103,  60, 296],
       [ 76,  76, 467, ..., 183, 496, 130],
       [212, 418, 279, ..., 296, 108, 438]])

## point to remember

1. for one matrix ()
2. for 2d matrix (())
3. for 3d matrix ((()))

In [173]:
# example
ones = np.ones((5,5))
print(ones)

zeros = np.zeros((3,3))
zeros[1,1]=9
print(zeros)

ones[1:-1,1:-1]=zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### be carefull when you use array


In [174]:
a= np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


## MATHEMATICS

In [175]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [176]:
a + 2

array([3, 4, 5, 6])

In [177]:
a*2

array([2, 4, 6, 8])

In [178]:
a -2 

array([-1,  0,  1,  2])

In [179]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [180]:
a +=2
a

array([3, 4, 5, 6])

In [181]:
b = np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [182]:
a+b

array([4, 4, 6, 6])

In [183]:
a ** 2

array([ 9, 16, 25, 36])

In [184]:
# take sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [185]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

## LINERA ALGERBRA

In [186]:
a= np.ones((2,3))
a


array([[1., 1., 1.],
       [1., 1., 1.]])

In [187]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

#### Key Properties of np.matmul():
1. It performs dot product for 1D arrays (vectors).
2. It performs matrix multiplication for 2D arrays.
3. It follows broadcasting rules for higher-dimensional arrays.

In [188]:
np.matmul(a,b) # both the matrix has to belike tbis in the example

array([[6., 6.],
       [6., 6.]])

#### Step-by-Step Analysis
1. np.identity(3) creates a 3×3 identity matrix:
c
=
[
1
0
0
0
1
0
0
0
1
 
]
c= 
​	
  
1
0
0
​	
  
0
1
0
​	
  
0
0
1
​	
  
​	
 
The determinant of an identity matrix of any size 
n
×
n
n×n is always 1.
So, np.linalg.det(c) returns:

In [189]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## STATISTICS

In [190]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
np.min(stats)

1

In [192]:
np.max(stats)

6

In [193]:
np.min(stats,axis=0) #min of the first row

array([1, 2, 3])

In [194]:
np.sum(stats,axis=0)

array([5, 7, 9])

## REORGANIZING ARRAYS

In [195]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [196]:
before.shape

(2, 4)

In [197]:
after= before.reshape(4,2) # change the shape of the matrix
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [198]:
after= before.reshape(2,2,2) # change the shape of the matrix
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [199]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1,v2]) # join the two matrix into one

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [200]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1,v2,v1,v2])  # stack multiple

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [201]:
#horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##  MISCELLANEOUS

#### LOAD THE DATA FILE


In [202]:
data = np.genfromtxt('data.txt', delimiter=',')
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [203]:
data.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## ADVANCE INDEXING AND BOOLEAN MASKING


In [204]:
data > 60

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [205]:
data[data > 60]

array([196.,  75., 766.,  75., 999.,  78.,  76.,  88.])

In [207]:
#you can index with a list in numpy
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

### If at least one element is True (nonzero), it returns True.
### If all elements are False (zero), it returns False.

In [209]:
np.any(data>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

### If all elements are True (nonzero), it returns True.
### If at least one element is False (zero), it returns False.

In [ ]:
np.all(data>50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [211]:
((data>50) & (data<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [212]:
(~((data>50) & (data<100))) #!not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])