# LEANING NUMPY

In [2]:
import numpy as np

## THE BASICS

In [3]:
a = np.array([0,1,2,3,])
print(a)


[0 1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get the demention
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#get shape
a.shape

(4,)

In [8]:
b.shape

(2, 3)

In [9]:
# get the type
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('float64')

In [11]:
#gte sixe
a.itemsize

8

In [12]:
b.itemsize

8

In [13]:
# how to gwt total size
a.nbytes


32

In [14]:
b.nbytes

48

In [15]:
a.size * a.itemsize  #another way to do this

32

## ACCESSING/CHANGING SPECIFIC ELEMENTS , ROWS, COLOUMNS,ETS

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# get a specific element [r,c]
a[1,5]

13

In [18]:
a[1,-2]

13

In [19]:
# get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# get aspecific coloums
a[:,4]

array([ 5, 12])

In [21]:
#getting a lil more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [22]:
a[1,1:7:3]

array([ 9, 12])

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
a[0,1:-1:2]

array([2, 4, 6])

In [25]:
#how to change some value in the lsit
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
a[:,2]=5 #for coloumns
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [27]:
a[:,2]=[1,2] #for coloumns
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3-D EXAMPLE

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# get a specific element (work outside in)
b[0,1,1]

4

In [30]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b) # only works for arrays in same dimention

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## INTIAILIZING DIFFERIENT TYPES OF ARRAYS

In [ ]:
#all zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [35]:
# any other number 
np.full((2,2),99 ,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [37]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
# random decimal number
np.random.rand(4,2)

array([[0.53824221, 0.71816724],
       [0.09644665, 0.49545456],
       [0.57470265, 0.71280545],
       [0.71578573, 0.27523603]])

In [48]:
np.random.rand(0,100)

array([], shape=(0, 100), dtype=float64)

In [54]:
# random interget values
np.random.randint(4,7, size=(3,3))

array([[4, 6, 6],
       [6, 6, 5],
       [4, 5, 4]])

In [ ]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
#reapeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### FUNNN TIME 

1. import random 
2. generate 2 number 
3. now use that to define some shape
4. get the size of the array
5. generate those many number
5. fill the dimention with hose number

In [49]:
import random
random_rows= random.randint(1000,3000)
random_coloumns = random.randint(20,30)
random_num =np.zeros((random_rows,random_coloumns),dtype=int)
random_num.shape



(2905, 22)

In [50]:
for row in range(random_rows):
    for colomn in range(random_coloumns):
        random_num[row,colomn]=random.randint(50,500)
        

In [51]:
random_num

array([[136, 395, 232, ..., 350, 147, 413],
       [203, 216,  80, ...,  97, 237, 405],
       [390, 337,  63, ..., 105, 249, 264],
       ...,
       [164,  65,  53, ..., 491, 320, 404],
       [149,  67, 165, ..., 205, 276, 148],
       [448, 378, 443, ..., 301, 452, 378]])

## point to remember

1. for one matrix ()
2. for 2d matrix (())
3. for 3d matrix ((()))

In [75]:
# example
ones = np.ones((5,5))
print(ones)

zeros = np.zeros((3,3))
zeros[1,1]=9
print(zeros)

ones[1:-1,1:-1]=zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
