# LEANING NUMPY

In [1]:
import numpy as np

## THE BASICS

In [2]:
a = np.array([0,1,2,3,])
print(a)


[0 1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
#get the demention
a.ndim

1

In [5]:
b.ndim

2

In [ ]:
#get shape
a.shape

(4,)

In [7]:
b.shape

(2, 3)

In [8]:
# get the type
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

In [10]:
#gte sixe
a.itemsize

8

In [11]:
b.itemsize

8

In [13]:
# how to gwt total size
a.nbytes


32

In [14]:
b.nbytes

48

In [ ]:
a.size * a.itemsize  #another way to do this

32

## ACCESSING/CHANGING SPECIFIC ELEMENTS , ROWS, COLOUMNS,ETS

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# get a specific element [r,c]
a[1,5]

13

In [20]:
a[1,-2]

13

In [24]:
# get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# get aspecific coloums
a[:,4]

array([ 5, 12])

In [27]:
#getting a lil more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [28]:
a[1,1:7:3]

array([ 9, 12])

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [31]:
a[0,1:-1:2]

array([2, 4, 6])

In [33]:
#how to change some value in the lsit
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2]=5 #for coloumns
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
a[:,2]=[1,2] #for coloumns
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3-D EXAMPLE

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
# get a specific element (work outside in)
b[0,1,1]

4

In [ ]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b) # only works for arrays in same dimention

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## INTIAILIZING DIFFERIENT YPES OF ARRAYS